# Generated by Django 2.0.4 on 2018-04-22 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bucketlist',
            old_name='date_create',
            new_name='date_created',
        ),
    ]
